In [3]:
# Fix CUDA compatibility - use only TITAN RTX GPU (device 1)
# GTX 1080 Ti doesn't support CUDA 12.8 (requires compute >= 7.0)
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"  # Only use TITAN RTX

# Verify (after kernel restart, run this cell FIRST before any other cell)
import torch
print(f"Visible GPUs: {torch.cuda.device_count()}")
for i in range(torch.cuda.device_count()):
    print(f"  GPU {i}: {torch.cuda.get_device_name(i)}")

Visible GPUs: 1
  GPU 0: NVIDIA TITAN RTX

In [2]:
!nvidia-smi

Wed Jan 21 12:37:20 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti     Off |   00000000:1A:00.0 Off |                  N/A |
|100%   42C    P0             68W /  250W |       7MiB /  11264MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA TITAN RTX               Off |   00000000:3D:00.0 Off |                  N/A |
|101%   37C    P0             69W /  280W |       6MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA TITAN RTX               Off |   00000000:3E:00.0 Off |                  N/A |
|100%   41C    P8             22W /  280W |       9MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce GTX 1080 Ti     Off |   00000000:B2:00.0 Off |                  N/A |
|100%   23C    P8             14W /  250W |       7MiB /  11264MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            3345      G   /usr/lib/xorg/Xorg                        4MiB |
|    1   N/A  N/A            3345      G   /usr/lib/xorg/Xorg                        4MiB |
|    2   N/A  N/A            3345      G   /usr/lib/xorg/Xorg                        4MiB |
|    3   N/A  N/A            3345      G   /usr/lib/xorg/Xorg                        4MiB |
+-----------------------------------------------------------------------------------------+

In [2]:
!pip install transformers[sentencepiece] datasets sacrebleu rouge_score py7zr -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 55.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 37.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.3/141.3 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.7/413.7 kB 23.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 8.0 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [22]:
!pip install --upgrade accelerate
!pip uninstall -y transformers accelerate
!pip install transformers accelerate

Collecting accelerate
  Downloading accelerate-1.12.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (2.4.1)
Requirement already satisfied: packaging>=20.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (7.2.1)
Requirement already satisfied: pyyaml in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (2.9.1)
Requirement already satisfied: huggingface_hub>=0.21.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate) (2025.10.0)
Requirement already satisfied: requests in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.0)
Requirement already satisfied: setuptools in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2026.1.4)
Downloading accelerate-1.12.0-py3-none-any.whl (380 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.12.0
Found existing installation: transformers 4.57.6
Uninstalling transformers-4.57.6:
  Successfully uninstalled transformers-4.57.6
Found existing installation: accelerate 1.12.0
Uninstalling accelerate-1.12.0:
  Successfully uninstalled accelerate-1.12.0
Collecting transformers
  Using cached transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
Collecting accelerate
  Using cached accelerate-1.12.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (3.20.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (2.4.1)
Requirement already satisfied: packaging>=20.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (2026.1.15)
Requirement already satisfied: requests in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: psutil in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (7.2.1)
Requirement already satisfied: torch>=2.0.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from accelerate) (2.9.1)
Requirement already satisfied: setuptools in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from torch>=2.0.0->accelerate) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from requests->transformers) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/ajavindu/miniconda3/envs/lokesh/lib/python3.14/site-packages (from requests->transformers) (2026.1.4)
Using cached transformers-4.57.6-py3-none-any.whl (12.0 MB)
Using cached accelerate-1.12.0-py3-none-any.whl (380 kB)
Installing collected packages: transformers, accelerate
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [accelerate]2 [accelerate]
Successfully installed accelerate-1.12.0 transformers-4.57.6

In [4]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.3.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.10.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.13)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 7.1 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.3

In [2]:
import os
os.getcwd()

'/home/ajavindu/Radiomics/lokesh/Text-Summarizer/research'

In [4]:
from transformers import pipeline, set_seed
from datasets import load_dataset, load_from_disk
import matplotlib.pyplot as plt
from datasets import load_dataset
import pandas as pd
from datasets import load_dataset
import evaluate

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

import nltk
from nltk.tokenize import sent_tokenize

from tqdm import tqdm
import torch

# Set custom NLTK download directory
nltk_data_dir = "/home/ajavindu/Radiomics/lokesh"
nltk.data.path.append(nltk_data_dir)
nltk.download("punkt", download_dir=nltk_data_dir)

/home/ajavindu/miniconda3/envs/lokesh/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-01-21 12:37:30.510160: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[nltk_data] Downloading package punkt to
[nltk_data]     /home/ajavindu/Radiomics/lokesh...
[nltk_data]   Package punkt is already up-to-date!

/home/ajavindu/miniconda3/envs/lokesh/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-01-21 12:37:30.510160: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[nltk_data] Downloading package punkt to
[nltk_data]     /home/ajavindu/Radiomics/lokesh...
[nltk_data]   Package punkt is already up-to-date!

True

In [5]:
import os
# Use only TITAN RTX GPUs (compute capability 7.5) which are supported by CUDA 12.8
# os.environ["CUDA_VISIBLE_DEVICES"] = "1,2"

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:

model_ckpt = "google/pegasus-cnn_dailymail"

tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

model_pegasus = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-cnn_dailymail and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [13]:
!wget https://github.com/appsbotta/DataSets/raw/main/summarizer-data.zip
!unzip summarizer-data.zip

--2026-01-21 10:56:12--  https://github.com/appsbotta/DataSets/raw/main/summarizer-data.zip
Resolving github.com (github.com)... 20.207.73.82
Connecting to github.com (github.com)|20.207.73.82|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/appsbotta/DataSets/main/summarizer-data.zip [following]
--2026-01-21 10:56:13--  https://raw.githubusercontent.com/appsbotta/DataSets/main/summarizer-data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7903594 (7.5M) [application/zip]
Saving to: ‘summarizer-data.zip’

summarizer-data.zip 100%[===================>]   7.54M  96.3KB/s    in 1m 40s

2026-01-21 10:57:55 (76.9 KB/s) - ‘summarizer-data.zip’ saved [7903594/7903594]

Archive:  summarizer-data.zip
  inflating: samsum-test.csv
  inflating: samsum-train.csv
  inflating: samsum-validation.csv
   creating: samsum_dataset/
 extracting: samsum_dataset/dataset_dict.json
   creating: samsum_dataset/test/
  inflating: samsum_dataset/test/data-00000-of-00001.arrow
  inflating: samsum_dataset/test/dataset_info.json
  inflating: samsum_dataset/test/state.json
   creating: samsum_dataset/train/
  inflating: samsum_dataset/train/data-00000-of-00001.arrow
  inflating: samsum_dataset/train/dataset_info.json
  inflating: samsum_dataset/train/state.json
   creating: samsum_dataset/validation/
  inflating: samsum_dataset/validation/data-00000-of-00001.arrow
  inflating: samsum_dataset/validation/dataset_info.json
  inflating: samsum_dataset/validation/state.json

In [7]:
dataset_samsum = load_from_disk('samsum_dataset')
dataset_samsum

DatasetDict({
    train: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 14732
    })
    test: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 819
    })
    validation: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 818
    })
})

In [8]:
split_lengths = [len(dataset_samsum[split])for split in dataset_samsum]

print(f"Split lengths: {split_lengths}")
print(f"Features: {dataset_samsum['train'].column_names}")
print("\nDialogue:")

print(dataset_samsum["test"][1]["dialogue"])

print("\nSummary:")

print(dataset_samsum["test"][1]["summary"])

Split lengths: [14732, 819, 818]
Features: ['id', 'dialogue', 'summary']

Dialogue:
Eric: MACHINE!
Rob: That's so gr8!
Eric: I know! And shows how Americans see Russian ;)
Rob: And it's really funny!
Eric: I know! I especially like the train part!
Rob: Hahaha! No one talks to the machine like that!
Eric: Is this his only stand-up?
Rob: Idk. I'll check.
Eric: Sure.
Rob: Turns out no! There are some of his stand-ups on youtube.
Eric: Gr8! I'll watch them now!
Rob: Me too!
Eric: MACHINE!
Rob: MACHINE!
Eric: TTYL?
Rob: Sure :)

Summary:
Eric and Rob are going to watch a stand-up on youtube.

In [9]:
def convert_examples_to_features(example_batch):
    input_encodings = tokenizer(example_batch['dialogue'] , max_length = 1024, truncation = True )

    with tokenizer.as_target_tokenizer():
        target_encodings = tokenizer(example_batch['summary'], max_length = 128, truncation = True )

    return {
        'input_ids' : input_encodings['input_ids'],
        'attention_mask': input_encodings['attention_mask'],
        'labels': target_encodings['input_ids']
    }

In [10]:
dataset_samsum_pt = dataset_samsum.map(convert_examples_to_features, batched = True)

In [11]:
dataset_samsum_pt["train"]

Dataset({
    features: ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 14732
})

In [12]:
from transformers import DataCollatorForSeq2Seq

seq2seq_data_collator = DataCollatorForSeq2Seq(tokenizer, model=model_pegasus)

In [24]:
from transformers import TrainingArguments, Trainer

trainer_args = TrainingArguments(
    output_dir='pegasus-samsum',
    num_train_epochs=3,
    warmup_steps=200,
    per_device_train_batch_size=2,   # Increased from 1 to 2
    per_device_eval_batch_size=2,    # Increased from 1 to 2
    weight_decay=0.01,
    logging_steps=10,
    eval_strategy='steps',
    eval_steps=500,
    save_steps=500,
    save_total_limit=2,
    gradient_accumulation_steps=8,   # Reduced from 16 to 8 (effective batch still 16)
    fp16=True,
    learning_rate=1e-5,
    load_best_model_at_end=True,
    metric_for_best_model='eval_loss',
)

In [25]:
trainer = Trainer(model=model_pegasus, args=trainer_args,
                  tokenizer=tokenizer, data_collator=seq2seq_data_collator,
                  train_dataset=dataset_samsum_pt["train"],
                  eval_dataset=dataset_samsum_pt["validation"])

/tmp/ipykernel_1334407/3442823430.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(model=model_pegasus, args=trainer_args,

In [26]:
trainer.train()

There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=2763, training_loss=1.524503772085316, metrics={'train_runtime': 3348.1153, 'train_samples_per_second': 13.2, 'train_steps_per_second': 0.825, 'total_flos': 2.3051103051792384e+16, 'train_loss': 1.524503772085316, 'epoch': 3.0})

In [27]:
# Evaluation

def generate_batch_sized_chunks(list_of_elements, batch_size):
    """split the dataset into smaller batches that we can process simultaneously
    Yield successive batch-sized chunks from list_of_elements."""
    for i in range(0, len(list_of_elements), batch_size):
        yield list_of_elements[i : i + batch_size]


def calculate_metric_on_test_ds(dataset, metric, model, tokenizer,
                               batch_size=16, device="cuda",
                               column_text="article",
                               column_summary="highlights"):
    model.eval()  # Set model to evaluation mode
    article_batches = list(generate_batch_sized_chunks(dataset[column_text], batch_size))
    target_batches = list(generate_batch_sized_chunks(dataset[column_summary], batch_size))

    with torch.no_grad():  # Disable gradient computation for inference
        for article_batch, target_batch in tqdm(
            zip(article_batches, target_batches), total=len(article_batches)):

            inputs = tokenizer(article_batch, max_length=1024, truncation=True,
                            padding="max_length", return_tensors="pt")

            summaries = model.generate(input_ids=inputs["input_ids"].to(device),
                             attention_mask=inputs["attention_mask"].to(device),
                             length_penalty=0.8, num_beams=8, max_length=128)

            decoded_summaries = [tokenizer.decode(s, skip_special_tokens=True,
                                    clean_up_tokenization_spaces=True)
                   for s in summaries]

            decoded_summaries = [d.replace("<n>", " ") for d in decoded_summaries]

            metric.add_batch(predictions=decoded_summaries, references=target_batch)

    score = metric.compute()
    return score

In [28]:
rouge_names = ["rouge1", "rouge2", "rougeL", "rougeLsum"]
rouge_metric = evaluate.load('rouge')

In [29]:
score = calculate_metric_on_test_ds(
    dataset_samsum['test'], rouge_metric, trainer.model, tokenizer, batch_size = 2, column_text = 'dialogue', column_summary= 'summary'
)

rouge_dict = dict((rn, score[rn] ) for rn in rouge_names )

pd.DataFrame(rouge_dict, index = [f'pegasus'] )

100%|██████████| 410/410 [10:00<00:00,  1.46s/it]

           rouge1    rouge2    rougeL  rougeLsum
pegasus  0.444029  0.213753  0.354241   0.354245

In [30]:
# Quick test - what does the model actually generate?
test_dialogue = dataset_samsum['test'][0]['dialogue']
test_reference = dataset_samsum['test'][0]['summary']

inputs = tokenizer(test_dialogue, max_length=1024, truncation=True, return_tensors="pt").to(device)
output = trainer.model.generate(**inputs, max_length=128, num_beams=8, length_penalty=0.8)
generated = tokenizer.decode(output[0], skip_special_tokens=True)

print("DIALOGUE:")
print(test_dialogue[:500])
print("\nREFERENCE SUMMARY:")
print(test_reference)
print("\nMODEL GENERATED:")
print(generated)

DIALOGUE:
Hannah: Hey, do you have Betty's number?
Amanda: Lemme check
Hannah: <file_gif>
Amanda: Sorry, can't find it.
Amanda: Ask Larry
Amanda: He called her last time we were at the park together
Hannah: I don't know him well
Hannah: <file_gif>
Amanda: Don't be shy, he's very nice
Hannah: If you say so..
Hannah: I'd rather you texted him
Amanda: Just text him 🙂
Hannah: Urgh.. Alright
Hannah: Bye
Amanda: Bye bye

REFERENCE SUMMARY:
Hannah needs Betty's number but Amanda doesn't have it. She needs to contact Larry.

MODEL GENERATED:
Amanda can't find Betty's number. Larry called Betty last time they were at the park together. Hannah wants Amanda to text Larry. Amanda will text Larry.

In [31]:
## Save model
model_pegasus.save_pretrained("pegasus-samsum-model")

In [32]:
tokenizer.save_pretrained("tokenizer")

('tokenizer/tokenizer_config.json',
 'tokenizer/special_tokens_map.json',
 'tokenizer/spiece.model',
 'tokenizer/added_tokens.json',
 'tokenizer/tokenizer.json')

In [34]:
tokenizer = AutoTokenizer.from_pretrained("tokenizer")

In [36]:
# Inference with the saved model
gen_kwargs = {"length_penalty": 0.8, "num_beams": 8, "max_length": 64}  # Reduced for shorter dialogues

sample_text = dataset_samsum["test"][0]["dialogue"]
reference = dataset_samsum["test"][0]["summary"]

pipe = pipeline("summarization", model="pegasus-samsum-model", tokenizer=tokenizer, device=0)

print("Dialogue:")
print(sample_text)
print("\nReference Summary:")
print(reference)
print("\nModel Summary:")
print(pipe(sample_text, **gen_kwargs)[0]["summary_text"])

Device set to use cuda:0

Dialogue:
Hannah: Hey, do you have Betty's number?
Amanda: Lemme check
Hannah: <file_gif>
Amanda: Sorry, can't find it.
Amanda: Ask Larry
Amanda: He called her last time we were at the park together
Hannah: I don't know him well
Hannah: <file_gif>
Amanda: Don't be shy, he's very nice
Hannah: If you say so..
Hannah: I'd rather you texted him
Amanda: Just text him 🙂
Hannah: Urgh.. Alright
Hannah: Bye
Amanda: Bye bye

Reference Summary:
Hannah needs Betty's number but Amanda doesn't have it. She needs to contact Larry.

Model Summary:
Amanda can't find Betty's number. Larry called Betty last time they were at the park together. Hannah wants Amanda to text Larry. Amanda will text Larry.